In [1]:
import pandas as pd
messages=pd.read_csv('SMSSpamCollection',
                    sep='\t',names=["label","message"])

In [2]:
import numpy

In [3]:
## Data Cleaning And Preprocessing
import re
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\user\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [4]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [5]:
corpus=[]
for i in range(0,len(messages)):
    review=re.sub('[^a-zA-z]',' ',messages['message'][i])
    review=review.lower()
    review=review.split()
    review=[ps.stem(word) for word in review if not word in stopwords.words('english')]
    review=' '.join(review)
    corpus.append(review)

In [7]:
corpus

['go jurong point crazi avail bugi n great world la e buffet cine got amor wat',
 'ok lar joke wif u oni',
 'free entri wkli comp win fa cup final tkt st may text fa receiv entri question std txt rate c appli',
 'u dun say earli hor u c alreadi say',
 'nah think goe usf live around though',
 'freemsg hey darl week word back like fun still tb ok xxx std chg send rcv',
 'even brother like speak treat like aid patent',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press copi friend callertun',
 'winner valu network custom select receivea prize reward claim call claim code kl valid hour',
 'mobil month u r entitl updat latest colour mobil camera free call mobil updat co free',
 'gonna home soon want talk stuff anymor tonight k cri enough today',
 'six chanc win cash pound txt csh send cost p day day tsandc appli repli hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw',
 'search right word thank breather

In [8]:
## Output Features
y=pd.get_dummies(messages['label'])
y=y.iloc[:,0].values

In [9]:
y

array([ True,  True, False, ...,  True,  True,  True])

In [10]:
## Train Test Split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(corpus,y,test_size=0.20)

In [11]:
## Create the Bag OF Words model
from sklearn.feature_extraction.text import CountVectorizer
## for Binary BOW enable binary=True
cv=CountVectorizer(max_features=2500,ngram_range=(1,2))

In [12]:
len(X_test),len(y_test)

(1115, 1115)

In [13]:
## independent features
X_train=cv.fit_transform(X_train).toarray()
X_test=cv.transform(X_test).toarray()

In [14]:
X_test

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [15]:
cv.vocabulary_

{'hand': 882,
 'phone': 1560,
 'chat': 325,
 'wit': 2419,
 'dont': 548,
 'think': 2098,
 'need': 1403,
 'card': 291,
 'uk': 2223,
 'travel': 2170,
 'ask': 101,
 'someon': 1917,
 'gone': 814,
 'lt': 1210,
 'gt': 851,
 'buck': 225,
 'lt gt': 1212,
 'gt buck': 852,
 'also': 55,
 'didnt': 520,
 'get': 762,
 'na': 1389,
 'hi': 916,
 'didnt get': 521,
 'hi hi': 919,
 'free': 704,
 'text': 2078,
 'messag': 1287,
 'valid': 2288,
 'decemb': 494,
 'free text': 720,
 'mm': 1320,
 'time': 2120,
 'like': 1143,
 'fun': 739,
 'like fun': 1145,
 'complet': 394,
 'oh': 1475,
 'told': 2147,
 'come': 382,
 'wednesday': 2367,
 'two': 2199,
 'pleas': 1590,
 'went': 2390,
 'invit': 1015,
 'friend': 726,
 'repli': 1728,
 'ye': 2479,
 'see': 1809,
 'www': 2457,
 'sm': 1902,
 'ac': 4,
 'stop': 1985,
 'send': 1821,
 'frnd': 732,
 'invit friend': 1016,
 'friend repli': 727,
 'repli ye': 1732,
 'ye see': 2483,
 'see www': 1812,
 'www sm': 2460,
 'sm ac': 1903,
 'stop send': 1990,
 'send stop': 1826,
 'stop frnd':

In [16]:
## Data Cleaning And Preprocessing
import re
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\user\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [17]:
corpus=[]
for i in range(0,len(messages)):
    review=re.sub('[^a-zA-z]',' ',messages['message'][i])
    review=review.lower()
    review=review.split()
    review=[ps.stem(word) for word in review if not word in stopwords.words('english')]
    review=' '.join(review)
    corpus.append(review)

In [18]:
corpus

['go jurong point crazi avail bugi n great world la e buffet cine got amor wat',
 'ok lar joke wif u oni',
 'free entri wkli comp win fa cup final tkt st may text fa receiv entri question std txt rate c appli',
 'u dun say earli hor u c alreadi say',
 'nah think goe usf live around though',
 'freemsg hey darl week word back like fun still tb ok xxx std chg send rcv',
 'even brother like speak treat like aid patent',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press copi friend callertun',
 'winner valu network custom select receivea prize reward claim call claim code kl valid hour',
 'mobil month u r entitl updat latest colour mobil camera free call mobil updat co free',
 'gonna home soon want talk stuff anymor tonight k cri enough today',
 'six chanc win cash pound txt csh send cost p day day tsandc appli repli hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw',
 'search right word thank breather

In [19]:
## Output Features
y=pd.get_dummies(messages['label'])
y=y.iloc[:,0].values

In [20]:
y

array([ True,  True, False, ...,  True,  True,  True])

In [21]:
## Train Test Split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(corpus,y,test_size=0.20)

In [22]:
## Create the Bag OF Words model
from sklearn.feature_extraction.text import CountVectorizer
## for Binary BOW enable binary=True
cv=CountVectorizer(max_features=2500,ngram_range=(1,2))

In [23]:
len(X_test),len(y_test)

(1115, 1115)

In [24]:
## independent features
X_train=cv.fit_transform(X_train).toarray()
X_test=cv.transform(X_test).toarray()

In [25]:
X_test

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [26]:
cv.vocabulary_

{'time': 2116,
 'think': 2097,
 'need': 1400,
 'know': 1076,
 'near': 1398,
 'campu': 283,
 'need know': 1405,
 'keep': 1059,
 'see': 1806,
 'shit': 1855,
 'actual': 14,
 'reason': 1693,
 'oh': 1472,
 'dont': 552,
 'worri': 2436,
 'guess': 870,
 'busi': 230,
 'dont worri': 556,
 'work': 2430,
 'home': 943,
 'lol': 1170,
 'ye': 2479,
 'friendship': 739,
 'hang': 886,
 'caus': 308,
 'buy': 231,
 'stuff': 2003,
 'how': 963,
 'street': 1998,
 'end': 599,
 'librari': 1136,
 'walk': 2318,
 'place': 1579,
 'ur': 2236,
 'point': 1604,
 'modul': 1334,
 'alreadi': 52,
 'town': 2166,
 'ju': 1053,
 'take': 2041,
 'mrt': 1361,
 'later': 1097,
 'ok': 1475,
 'wif': 2394,
 'co': 364,
 'like': 1143,
 'tri': 2173,
 'new': 1413,
 'thing': 2096,
 'dun': 573,
 'mah': 1223,
 'said': 1772,
 'hey': 913,
 'si': 1867,
 'huh': 972,
 'want': 2326,
 'sex': 1846,
 'sec': 1800,
 'ring': 1748,
 'cost': 433,
 'min': 1288,
 'pobox': 1600,
 'wc': 2353,
 'xx': 2468,
 'wc xx': 2354,
 'anyth': 76,
 'regard': 1707,
 'idk': 

In [27]:
from sklearn.naive_bayes import MultinomialNB

In [28]:
spam_detect_model=MultinomialNB().fit(X_train,y_train)

In [29]:
spam_detect_model


MultinomialNB()

In [30]:
y_pred=spam_detect_model.predict(X_test)

In [31]:
from sklearn.metrics import accuracy_score,classification_report

In [32]:
accuracy_score(y_test,y_pred)

0.9856502242152466

In [33]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

       False       0.94      0.93      0.94       128
        True       0.99      0.99      0.99       987

    accuracy                           0.99      1115
   macro avg       0.97      0.96      0.96      1115
weighted avg       0.99      0.99      0.99      1115



In [34]:
## Train Test Split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(corpus,y,test_size=0.20)

In [35]:
from sklearn.feature_extraction.text import TfidfVectorizer
tv=TfidfVectorizer(max_features=2500,ngram_range=(1,2))
X_train=tv.fit_transform(X_train).toarray()
X_test=tv.transform(X_test).toarray()

In [36]:
X_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [37]:
tv.vocabulary_

{'like': 1156,
 'think': 2102,
 'alway': 59,
 'possibl': 1613,
 'pub': 1650,
 'later': 1113,
 'hey': 930,
 'tmr': 2138,
 'meet': 1273,
 'bugi': 233,
 'ye': 2476,
 'come': 381,
 'tri': 2177,
 'open': 1494,
 'transact': 2173,
 'refer': 1704,
 'number': 1454,
 'lt': 1213,
 'gt': 867,
 'rs': 1759,
 'decim': 501,
 'credit': 445,
 'account': 10,
 'time': 2125,
 'refer number': 1705,
 'lt gt': 1215,
 'gt rs': 875,
 'lt decim': 1214,
 'decim gt': 502,
 'gt lt': 872,
 'lt time': 1216,
 'time gt': 2129,
 'today': 2143,
 'song': 1924,
 'dedic': 504,
 'day': 482,
 'send': 1817,
 'ur': 2241,
 'frnd': 753,
 'first': 698,
 'rpli': 1758,
 'song dedic': 1925,
 'send ur': 1826,
 'havent': 913,
 'got': 847,
 'da': 470,
 'yet': 2490,
 'rite': 1746,
 'issu': 1044,
 'right': 1740,
 'ill': 1005,
 'fix': 701,
 'tomorrow': 2150,
 'told': 2148,
 'return': 1735,
 'order': 1504,
 'great': 859,
 'aunt': 125,
 'parti': 1525,
 'hello': 926,
 'darl': 476,
 'would': 2443,
 'love': 1199,
 'chat': 327,
 'dont': 553,
 't

In [38]:
from sklearn.naive_bayes import MultinomialNB
spam_tfidf_model = MultinomialNB().fit(X_train, y_train)

In [39]:
#prediction
y_pred=spam_tfidf_model.predict(X_test)

In [40]:
score=accuracy_score(y_test,y_pred)
print(score)

0.9856502242152466


In [41]:
from sklearn.metrics import classification_report
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

       False       0.88      1.00      0.94       123
        True       1.00      0.98      0.99       992

    accuracy                           0.99      1115
   macro avg       0.94      0.99      0.97      1115
weighted avg       0.99      0.99      0.99      1115

